// <auto-generated />
namespace restaurant_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deleteLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201710091021297_deleteLocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
