// <auto-generated />
namespace restaurant_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newrow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newrow));
        
        string IMigrationMetadata.Id
        {
            get { return "201709111127092_newrow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
