// <auto-generated />
namespace restaurant_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newrow11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newrow11));
        
        string IMigrationMetadata.Id
        {
            get { return "201709130734086_newrow11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
